name: Build Android APK And Upload
on:
  push:
    branches:
      - repo4
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Getting the repo
        uses: actions/checkout@v2
      - name: Install gpg
        run: sudo apt-get install gnupg
      - name: Decrypt Secretes
        env:
          SSH_KEY_ENCRYPTION_PASSPHRASE: ${{ secrets.SSH_KEY_ENCRYPTION_PASSPHRASE }}
          SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Clone Private Repo
        env:
          PRIVATE_REPO_SSH_URL: ${{ secrets.REPO_4_SSH_URL }}
          PRIVATE_REPO_BRANCH: ${{ secrets.REPO_4_BRANCH }}
        run: ./.github/scripts/clone_repo.sh
      - name: Install dependencies
        run: ./.github/scripts/install_dependancies_android.sh
      - name: Download bitcode
        run: ./private_repo/node_modules/react-native-webrtc/tools/downloadBitcode.sh
      - name: Build android
        env:
          ANDROID_KEY_STORE_PASSWORD: ${{ secrets.REPO_4_ANDROID_KEY_STORE_PASSWORD }}
          ANDROID_ALIAS: ${{ secrets.REPO_4_ANDROID_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.REPO_4_ANDROID_KEY_PASSWORD }}
        run: |
          echo ${{ secrets.REPO_4_ANDROID_SIGNING_KEY }} | base64 --decode > private_repo/android/app/production.keystore
          cd private_repo/android && ./gradlew :app:bundleRelease
      - name: Upload App to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.REPO_4_ANDROID_SERVICE_ACCOUNT_JSON_TEXT }}
          packageName: ${{ secrets.REPO_4_ANDROID_PACKAGE_NAME }}
          releaseFiles: private_repo/android/app/build/outputs/bundle/release/*.aab
          track: internal
          status: draft
          inAppUpdatePriority: 2
      - name: Remove Private Repo
        run: ./.github/scripts/remove_repo.sh


