name: Build Android APK And Upload
on:
  push:
    branches:
      - android-private-repo
jobs:
  build-android:
    runs-on: macOS-latest
    steps:
      - name: Getting the repo
        uses: actions/checkout@v2
      - name: Clone The Private Repo
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Install gpg
        run: brew install gnupg
      - name: Clone Private Repo
        env:
          SSH_KEY_ENCRYPTION_PASSPHRASE: ${{ secrets.SSH_KEY_ENCRYPTION_PASSPHRASE }}
          SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Install dependencies
        run: ./.github/scripts/install_dependancies.sh


