name: Build iOS TestFlight
on:
  push:
    branches:
      - ios-private-repo
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
#      - name: Install dependencies
#        run: ./.github/scripts/install_dependancies.sh
      - name: Install gpg
        run: brew install gnupg
      - name: Decrypt Secretes
        env:
          SSH_KEY_ENCRYPTION_PASSPHRASE: ${{ secrets.SSH_KEY_ENCRYPTION_PASSPHRASE }}
          SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Setup provisioning profile
        env:
          PRIVATE_REPO_SSH_URL: ${{ secrets.PRIVATE_REPO_SSH_URL }}
        run: ./.github/secrets/clone_repo.sh
#      - name: Build IOS App
#        uses: yukiarrr/ios-build-action@v1.4.0
#        with:
#          project-path: ios/github.xcodeproj
#          p12-base64: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_BASE64 }}
#          mobileprovision-base64: ${{ secrets.APPLE_PROVISION_PROFILE_BASE64 }}
#          code-signing-identity: 'iPhone Distribution'
#          team-id: ${{ secrets.APPLE_TEAM_ID }}
#          certificate-password: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
#          workspace-path: ios/github.xcworkspace
#      - name: Upload Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: Github IOS IPA
#          path: 'output.ipa'
#      - name: 'Upload app to TestFlight'
#        uses: apple-actions/upload-testflight-build@v1
#        with:
#          app-path: 'output.ipa'
#          issuer-id: ${{ secrets.APPLE_APPSTORE_ISSUER_ID }}
#          api-key-id: ${{ secrets.APPLE_APPSTORE_API_KEY_ID }}
#          api-private-key: ${{ secrets.APPLE_APPSTORE_API_PRIVATE_KEY }}
