name: Build iOS TestFlight
on:
  push:
    branches:
      - ios-private-repo
jobs:
  deploy:
    name: Deploying to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Install gpg
        run: brew install gnupg
      - name: Decrypt Secretes
        env:
          SSH_KEY_ENCRYPTION_PASSPHRASE: ${{ secrets.SSH_KEY_ENCRYPTION_PASSPHRASE }}
          SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Clone Private Repo
        env:
          PRIVATE_REPO_1_SSH_URL: ${{ secrets.PRIVATE_REPO_1_SSH_URL }}
        run: ./.github/scripts/clone_repo.sh
      - name: Install dependencies
        run: ./.github/scripts/install_dependancies.sh
      - name: Build IOS App
        uses: yukiarrr/ios-build-action@v1.4.0
        with:
          project-path:
          p12-base64: ${{ secrets.REPO_1_XCODEPROJ_PATH }}
          mobileprovision-base64: ${{ secrets.REPO_1_APPLE_PROVISION_PROFILE_BASE64 }}
          code-signing-identity: 'iPhone Distribution'
          team-id: ${{ secrets.REPO_1_APPLE_TEAM_ID }}
          certificate-password: ${{ secrets.REPO_1_APPLE_CERTIFICATE_PASSWORD }}
          workspace-path: ${{ secrets.REPO_1_XCWORKSPACE_PATH }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Github IOS IPA
          path: 'output.ipa'
      - name: 'Upload app to TestFlight'
        uses: apple-actions/upload-testflight-build@v1
        with:
          app-path: 'output.ipa'
          issuer-id: ${{ secrets.APPLE_APPSTORE_ISSUER_ID }}
          api-key-id: ${{ secrets.APPLE_APPSTORE_API_KEY_ID }}
          api-private-key: ${{ secrets.APPLE_APPSTORE_API_PRIVATE_KEY }}
